[build]
  command = "CI=true npm run build"
  publish = "dist"

[dev]
  command = "npm run start"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[functions]
  directory = "functions/"
